# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.IntegerField()),
                ('street_no', models.IntegerField()),
                ('street', models.CharField(max_length=200)),
                ('street2', models.CharField(max_length=200, null=True)),
                ('suburb', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('QLD', 'Queensland'), ('NT', 'Northern Territory'), ('NSW', 'New South Wales'), ('VIC', 'Victoria'), ('TAS', 'Tasmania'), ('SA', 'South Australia'), ('WA', 'Western Australia'), ('ACT', 'Australian Capital Territory')], max_length=100)),
                ('postal_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen', models.BooleanField()),
                ('swimming_pool', models.BooleanField()),
                ('internet', models.BooleanField()),
                ('wireless', models.BooleanField()),
                ('bbq', models.BooleanField()),
                ('parking', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_type', models.CharField(choices=[('K', 'King'), ('Q', 'Queen'), ('D', 'Double'), ('S', 'Single'), ('SF', 'Sofa Bed'), ('M', 'Mattress'), ('WM', 'Water Mattress'), ('AM', 'Air Mattress'), ('T', 'Toddler Bed')], max_length=20)),
                ('num_of_beds', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bedroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedroom_no', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=7)),
                ('max_guests', models.IntegerField()),
                ('parking', models.IntegerField()),
                ('num_of_bathroom', models.IntegerField()),
                ('area', models.IntegerField()),
                ('description', models.TextField()),
                ('owner', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=500)),
                ('img_type', models.CharField(choices=[('T', 'Thumbnail'), ('E', 'Exterior'), ('I', 'Interior')], max_length=20)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Houses.House')),
            ],
        ),
        migrations.AddField(
            model_name='bedroom',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Houses.House'),
        ),
        migrations.AddField(
            model_name='bed',
            name='bedroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Houses.Bedroom'),
        ),
        migrations.AddField(
            model_name='amenity',
            name='house',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Houses.House'),
        ),
        migrations.AddField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Houses.Customer'),
        ),
        migrations.AddField(
            model_name='address',
            name='house',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Houses.House'),
        ),
    ]
