# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0002_auto_20170820_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
